/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game.view;

import game.entity.Evento;
import game.entity.Usuario;
import game.util.HibernateUtil;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Criteria;
import org.hibernate.Query;
import org.hibernate.Session;

/**
 *
 * @author UNIVASF
 */
public class Presenca extends javax.swing.JDialog {

    /**
     * Creates new form Presenca
     */
    private ArrayList<Usuario> usuarioA;

    public Presenca(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        Criteria c = session.createCriteria(Evento.class);
        ArrayList<Evento> eventoA = (ArrayList<Evento>) c.list();
        Criteria c1 = session.createCriteria(Usuario.class);
        usuarioA = (ArrayList<Usuario>) c1.list();
        session.getTransaction().commit();

        eventoA.forEach((evento1) -> {
            cbEventos.addItem(evento1);
        });
        session.flush();
        session.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbPresenca = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        cbEventos = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaDeParticipantes = new javax.swing.JTable();
        btnSalvarPresenca = new javax.swing.JButton();

        cbPresenca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Faltou", "Presente" }));
        cbPresenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPresencaActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Presença dos inscritos");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        cbEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEventosActionPerformed(evt);
            }
        });

        tblListaDeParticipantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "E-mail", "Telefone", "Endereço", "Curso", "Instituição", "Data de Nascimento", "Sexo", "Presença"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblListaDeParticipantes);
        if (tblListaDeParticipantes.getColumnModel().getColumnCount() > 0) {
            tblListaDeParticipantes.getColumnModel().getColumn(9).setCellEditor(new javax.swing.DefaultCellEditor(cbPresenca));
        }

        btnSalvarPresenca.setText("Salvar Presença");
        btnSalvarPresenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarPresencaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbEventos, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(391, 391, 391)
                        .addComponent(btnSalvarPresenca)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(cbEventos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalvarPresenca)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEventosActionPerformed
        // TODO add your handling code here:
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();

        Evento eventoCb = (Evento) cbEventos.getSelectedItem();

        String hql = "select rel.usuario from RUsuarioEvento rel where rel.evento.pkCodEvent like :CODIGO_EVENTO";
        Query query = session.createQuery(hql);
        query.setString("CODIGO_EVENTO", eventoCb.getPkCodEvent().toString());
        usuarioA = (ArrayList<Usuario>) query.list();

        DefaultTableModel tabelaDeUsuarios = (DefaultTableModel) tblListaDeParticipantes.getModel();
        Object[] usuariosV = new Object[tabelaDeUsuarios.getColumnCount()];
        
        tabelaDeUsuarios.setRowCount(0);

        for (int i = 0; i < usuarioA.size(); i++) {
            usuariosV[0] = usuarioA.get(i).getNome();
            usuariosV[1] = usuarioA.get(i).getPkCpf();
            usuariosV[2] = usuarioA.get(i).getEmail();
            usuariosV[3] = usuarioA.get(i).getTelefone();
            usuariosV[4] = usuarioA.get(i).getEndereco();
            usuariosV[5] = usuarioA.get(i).getCurso();
            usuariosV[6] = usuarioA.get(i).getInstituicao();
            usuariosV[7] = usuarioA.get(i).getDataNasc();
            usuariosV[8] = usuarioA.get(i).getSexo();
            tabelaDeUsuarios.addRow(usuariosV);
        }

        session.getTransaction().commit();
    }//GEN-LAST:event_cbEventosActionPerformed

    private void btnSalvarPresencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarPresencaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarPresencaActionPerformed

    private void cbPresencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPresencaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPresencaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Presenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Presenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Presenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Presenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Presenca dialog = new Presenca(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvarPresenca;
    private javax.swing.JComboBox<Object> cbEventos;
    private javax.swing.JComboBox<String> cbPresenca;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListaDeParticipantes;
    // End of variables declaration//GEN-END:variables
}
